### ISSUE TITLE
Error trying to compile standAloneKinematicsDemo1

### ISSUE THREAD

**Issue by santdiego** [CoppeliaRobotics/coppeliaKinematicsRoutines#1]
Hi. When trying to compile the example "standAloneKinematicsDemo1" I get the multiple errors in coppeliaKinematicsRoutines\sceneObject.cpp: 

- error: C2065: 'simOne': undeclared identifier

- error: C2065: 'simZero': undeclared identifier

- sceneObject.cpp:98: error: C2660: 'C4Vector::setAngleAndAxis': function does not take 1 arguments

**Comment by Coppelia** [comment]
Hello,
the Coppelia Kinematics Routines also depend on [simMath](https://github.com/CoppeliaRobotics/simMath)
Make sure to have that one also present in the programming folder.

Cheers
